language: go
go_import_path: github.com/rdsubhas/go-elastictable
go:
- 1.13
script:
- gofmt -d -s -e . 2>&1 | tee -a fmt.out
- test ! -s fmt.out
- go run golang.org/x/lint/golint -set_exit_status .
- go test ./...
notifications:
  email: false
